initial commit homework-1
OleksandrGlushchuk/Homeworks1 pull request #1
Opened 2022-05-02 21:29 UTC by OleksandrGlushchuk

2022-05-03 08:28 UTC, DmitrySarafaniuk commented
1. Это неплохо, когда можно использовать уже написанный кем-то код, но я бы советовал стараться писать сначала свой и параллельно подсматривать идеи других разработчиков, а не просто большую часть копировать. В будущем, когда задачи будут усложняться, найти код будет проблематично и нужно будет его писать самому, а без полного понимания того, как должна работать задача, это будет сделать сложно.
2. Пока делаете свою математику то я бы вынес операции по типу length, squared_length, make_unit_vector так же, как вынесены dot и cross, чтобы легче можно было использовать существующие функции (например dot в length). То есть вектор, матрицу и т.д. реализовать с уклонов в представление данных, а функции над ними выделять отдельно. Когда будет DirectX и разрешат использовать сторонние библиотеки, то лучше на написание своей математики время не тратить.
3. Выносить не inline функции из .h в .cpp файл (например, sphere.h), чтобы не было переопределения функций при включении хедера больше 1 раза. Также это ускорит компиляцию (у меня в классе камеры была обработка поворота и, когда я делал изменения, то большое количество файлов нужно было перекомпилировать - не удобно).
4. Членам классов и структур, аргументам функций и переменным лучше вырабатывать привычку давать самораскрывающие имена или писать комментарий (например в ray вместо A - origin). Сейчас это может казаться излишним, но в будущем всё равно придётся к этому прийти.
5. Можно сделать небольшие упрощения пересечения луча и сферы:
При поиске пересечения луча и сферы, из дискриминанта можно вынести 4 за корень, при этом, т.к при нахождении корня, мы делим на 2 - вынесенное значение из дискриминанта просто сократится.
Можно написать так: float b = dot(...); float discriminant = b * b - a * c;
Когда дискриминант больше или равен 0 - можно сразу взять в корень, чтобы не брать корень два раза.
Если мы можем гарантировать, что r.direction() нормализировано, то мы можем не считать 'a' при расчётах дискриминанта, т.к 'a' будет равняться 1.
Считаю это не критичным, но иногда такие вещи могут помогать. Например, для nintendo switch выполнение векторных и скалярных операций зачастую довольно времязатратные и даже переход в одной функции на intrinsic операции или упрощенные вычисления может дать прирост в 0.3мс. Просто нужно держать такой вариант в голове.
6. В функцию hit было бы неплохо передавать hit_record и записывать туда точку, где луч попал в объект, нормаль поверхности и т.д., вместо того чтобы просто возвращать true или false.
7. Лучше main.cpp не нагромождать лишним функционалом. Можно сделать класс Window и там проводить message processing.
8. Желательно было бы добавить дельту обновления кадра - когда захочется пересмотреть задания на рабочей машине, то всё равно придется это сделать. Для этого тоже можно сделать минимальный класс Timer.
9. Из WM_SIZE и WM_MOUSEMOVE лучше убрать логику рендеринга. Из функции Render убрать логику обработки ввода.
10. Под логику с рендерингом лучше выделить свой класс или хотя бы функцию (вижу, что она есть, но в ней много лишнего), то же самое с обработкой ввода.
11. Sleep(16); не нужен. Когда обработка ввода и рендеринг будут отделены, то PeekMessage(&msg, NULL, 0, 0, PM_REMOVE) можно будет обернуть в while
12. Желательно добавить поддержку ресайза окна.

Вот пункты по важности 7, 9, 10, 3, 8. Лучше было бы сделать все пункты, которые перечислил, так как это не полный список.
Но по факту программа работает относительно быстро, так что неплохо, просто масштабировать с такой концепцией будет сложно.

2022-05-03 09:22 UTC, mrindieperson requested changes

2022-05-03 09:22 UTC, mrindieperson commented on homework-1/engine/window/render.cpp
> +	BitBlt(device_context, 0, 0, screen.right, screen.bottom, compatible_context, 0, 0, SRCCOPY);
Попробуй переделать и рисовать не через BitBlt, а через SetDIBitsToDevice. Там можно будет просто буффер данных скармливать в окно и не нужные никакие дополнительные HBITMAP создавать

2022-05-03 09:22 UTC, mrindieperson commented on homework-1/engine/window/render.cpp
> +				SetPixel(compatible_context, x, y, RGB(255, 0, 0));
Если бы использовал SetDIBitsToDevice, то тут была бы просто запись в буфер данных, не нужно было бы SetPixel тут вызывать из WinApi, было бы быстрее. Хотя может можно как-то вытащить из HBITMAP указатель на сырые данные, я не помню.

Но попробуй сделать через SetDIBitsToDevice, тогда эти SelectObject выше всякие будут не нужны. И вызов Rectangle тебе не понадобится, ты бы мог просто красить сам в цвет фона, если нет попадения в сферу

2022-05-03 09:22 UTC, mrindieperson commented on homework-1/engine/window/render.h
> +	class Input_processing
Input_processing класс ты можешь переименовать в Controller и перенести в другой файл. Раз это render.h, зачем тут иметь код, отвечающий за игровую логику, пусть это будет в другом вообще месте.

И убери все static в этих файлах, пусть Render и Controller будут иметь инстансы, объявленные где-то перед главным циклом, и Controller будет иметь ссылку/указатель на Render, чтобы он мог им управлять

2022-05-03 09:22 UTC, mrindieperson commented on homework-1/engine/window/window.cpp
> +		Sleep(16);
Нет, это не даст нам 60 FPS. Во-первых длительность кадра при 60 FPS равна 1.f / 60.f, а это не 16 мс, во-вторых Sleep может в реальности длиться дольше, чем нам нужно, мы просто проспим момент. Здесь нужно использовать std::this_thread::yield() и проверять время, нужно ли нам рисовать или нет. К тому же сообщения WinApi нужно пикать постоянно, иначе будут фризы в инпуте из-за Sleep на 16 мс. Я в подсказке к решению вроде это описал. И явно используй константу FRAME_DURATION объявленную, не используй магическое число 16 в самом коде

2022-05-03 09:22 UTC, mrindieperson commented on homework-1/engine/math/sphere.cpp
> +                record.t = -999.999;
Используй для t значение std::numeric_limits<float>::infinity(), если решение не найдено, вместо этих непонятных констант, и вообще всегда, когда нужно найти минимальное/максимальное float значение. Вектор кстати можно и не инициализировать, проще у hit_record добавить геттер bool isValid() const, который проверяет, что t не бесконечность

2022-05-03 14:07 UTC, OleksandrGlushchuk commented on homework-1/engine/window/render.cpp
> +	BitBlt(device_context, 0, 0, screen.right, screen.bottom, compatible_context, 0, 0, SRCCOPY);
+-

2022-05-03 14:07 UTC, OleksandrGlushchuk commented on homework-1/engine/window/render.cpp
> +				SetPixel(compatible_context, x, y, RGB(255, 0, 0));
+-

2022-05-03 14:08 UTC, OleksandrGlushchuk commented on homework-1/engine/window/render.h
> +	class Input_processing
++

2022-05-03 14:08 UTC, OleksandrGlushchuk commented on homework-1/engine/window/window.cpp
> +		Sleep(16);
++

2022-05-03 14:08 UTC, OleksandrGlushchuk commented on homework-1/engine/math/sphere.cpp
> +                record.t = -999.999;
++

2022-05-03 14:49 UTC, mrindieperson requested changes

2022-05-03 14:49 UTC, mrindieperson commented on homework-1/engine/window/window.cpp
> +Controller Window::controller = Window::render;
Класс Window у тебя сейчас не является Window как таковым. Здесь намешан код логики окна, типо метод ::Show, и в общем-то код из main.cpp. То есть ты просто переместил всякие высокоуровневые вещи типо объявление Controller и главный цикл в ::Run в этот файл, по сути скопировал main.cpp то есть в window.cpp и вызывал его из main.cpp

Попробуй в Window оставить только то, что реально относится к окну: screen, device_context. Остальное, в том числе главный цикл, render, controller, функцию обработку событий ОС WndProc (окон может быть несколько, WndProc не привязан к конкретному окну) вынеси обратно в main.cpp

Также перемести image и bitmap_info из Render в Window. Пусть просто Render::Draw принимает ссылку на Window и рисует в любое окно, которое ему предоставят. Буффер пикселей окна по логике принадлежит Window , а не другому классу

2022-05-03 14:49 UTC, mrindieperson commented on homework-1/engine/window/window.cpp
> +	if (clock() - start >= seconds*CLOCKS_PER_SEC)
Перенеси это либо наружу в main.cpp, либо сделай частью Controller. Но не используй static переменную здесь

2022-05-03 14:49 UTC, mrindieperson commented on homework-1/engine/window/window.h
> +	static Render render;
А здесь ты не избавился от static, оставь в Window не static только screen и device_context, остальное не принадлежит Window

2022-05-03 14:52 UTC, mrindieperson commented on homework-1/engine/window/render.cpp
> +	image = new RGBQUAD[screen.right * screen.bottom];
Не используй никогда new в таких случаях просто так. Используй std::unique_ptr.

Но ещё проще здесь вообще использовать std::vector\<RGBQUAD\>. Зачем с сырыми указателями работать, если уже есть обёртки

2022-05-03 18:02 UTC, OleksandrGlushchuk commented on homework-1/engine/window/render.cpp
> +	image = new RGBQUAD[screen.right * screen.bottom];
++

2022-05-03 18:02 UTC, OleksandrGlushchuk commented on homework-1/engine/window/window.h
> +	static Render render;
++

2022-05-03 18:02 UTC, OleksandrGlushchuk commented on homework-1/engine/window/window.cpp
> +	if (clock() - start >= seconds*CLOCKS_PER_SEC)
++

2022-05-03 18:02 UTC, OleksandrGlushchuk commented on homework-1/engine/window/window.cpp
> +Controller Window::controller = Window::render;
++

2022-05-03 18:17 UTC, mrindieperson commented on homework-1/engine/main.cpp
> +	if (clock() - start >= seconds * CLOCKS_PER_SEC)
Вместо всего этого используй std::chrono, пожалуйста, в частности steady_clock. Там понадобится делать duration_cast\<float\> между моментами времени и сравнивать разницу времени с константой const float FRAME_DURATION = 1.f / 60.f;

2022-05-03 18:19 UTC, mrindieperson commented on homework-1/engine/main.cpp
> +			controller.OnKeyDown();
Это по факту скорее controller.processInput метод, лучше переименовать

2022-05-03 18:20 UTC, mrindieperson commented on homework-1/engine/window/render.cpp
> +void Render::DrawOn(Window& wnd)
Зачем эти постфиксы On. Если уже как параметр приходит Window, уже понятно, что это рисуется в окно это

2022-05-03 18:26 UTC, mrindieperson commented on homework-1/engine/window/render.cpp
> +void Render::Init(Window& wnd)
Render является более низкоуровневым классом, чем Window, он не должен управлять им, Render только рисовать должен в окно какое бы оно ни было.

Этот метод Render::Init не нужен, вынеси его в Controller просто наружу

2022-05-03 18:29 UTC, mrindieperson commented on homework-1/engine/main.cpp
> +		controller.OnChangeWindowSize(window);
Можно было бы просто вызвать window.onResize() тут, чтобы ресайзить окно, это бы заменило вызов UpdateWindowSize() и render.Init(Window) на один логичный вызов window.onResize()

А следующей строкой можно вызвать controller.OnChangeWindowSize, который бы уже внутри себя центрировал бы сферу в окне + перерисовал бы окно

2022-05-03 18:30 UTC, mrindieperson commented on homework-1/engine/window/window.h
> +inline void UpdateWindowSize(Window& wnd)
Эта функция некрасиво тут выглядит, этот код мог бы быть, как я выше описал, часть вызова Window::onResize

2022-05-03 19:17 UTC, DmitrySarafaniuk commented
LRESULT WndProc(...) лучше будет в будущем перенести в Window, а не оставлять в main

2022-05-04 05:56 UTC, OleksandrGlushchuk commented on homework-1/engine/main.cpp
> +	if (clock() - start >= seconds * CLOCKS_PER_SEC)
++

2022-05-04 05:56 UTC, OleksandrGlushchuk commented on homework-1/engine/main.cpp
> +			controller.OnKeyDown();
++

2022-05-04 05:56 UTC, OleksandrGlushchuk commented on homework-1/engine/window/render.cpp
> +void Render::DrawOn(Window& wnd)
++

2022-05-04 05:56 UTC, OleksandrGlushchuk commented on homework-1/engine/window/render.cpp
> +void Render::Init(Window& wnd)
++

2022-05-04 05:56 UTC, OleksandrGlushchuk commented on homework-1/engine/main.cpp
> +		controller.OnChangeWindowSize(window);
++

2022-05-04 05:56 UTC, OleksandrGlushchuk commented on homework-1/engine/window/window.h
> +inline void UpdateWindowSize(Window& wnd)
++

2022-05-04 13:17 UTC, mrindieperson commented
✅ всё гуд, молодец

2022-05-04 13:21 UTC, DmitrySarafaniuk commented
✅:+1:

2022-05-04 17:10 UTC, merged