Initial commit homework-3
OleksandrGlushchuk/Homeworks1 pull request #3
Opened 2022-06-07 08:37 UTC by OleksandrGlushchuk

2022-06-08 07:59 UTC, DmitrySarafaniuk commented on RenderProject/engine/math/Light.h
> +	float solid_angle = M_PI * new_radius * new_radius;
Сейчас solid_angle сводится к квадратному затуханию после деления на HALF_SPHERE_SOLID_ANGLE. Тут есть [вариант нахождения]( https://math.stackexchange.com/questions/73238/calculating-solid-angle-for-a-sphere-in-space) телесного угла.

2022-06-08 08:00 UTC, DmitrySarafaniuk commented
Вынеси Exposure, ACES и т.п. в другой файл, например в файл PostProcess.

2022-06-08 08:01 UTC, DmitrySarafaniuk commented on RenderProject/engine/window/Scene.cpp
> +}
Лучше это тоже вынести либо в vec3, либо в ray.

2022-06-08 08:04 UTC, FantasticMrF0x commented on RenderProject/engine/window/Scene.cpp
> +void Scene::�orrectLight(Vec3& light)
Лучше переназвать в ToneMapping или что-то подобное.

2022-06-08 08:06 UTC, DmitrySarafaniuk commented
Сделай изменения, пожалуйста, с Q/E/Shift (то, что по заданию добавили).

2022-06-08 08:28 UTC, OleksandrGlushchuk commented
> Сделай изменения, пожалуйста, с Q/E/Shift (то, что по заданию добавили).

++

2022-06-08 08:32 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/Scene.cpp
> +}
++

2022-06-08 08:50 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/Scene.cpp
> +void Scene::�orrectLight(Vec3& light)
++

2022-06-08 09:35 UTC, OleksandrGlushchuk commented
> PostProcess

++

2022-06-08 09:57 UTC, OleksandrGlushchuk commented on RenderProject/engine/math/Light.h
> +	float solid_angle = M_PI * new_radius * new_radius;
++

2022-06-08 19:21 UTC, mrindieperson commented
- Почему нет уменьшения разрешения по осям в 2 раза с прошлого задания? Тормозит иначе при даже небольшом окне
- Кнопка R не должна 100 раз в секунду переключать видимость гладких отражений пока зажата, один раз при нажатии только меняется , игнорируй повторные события, которые для печати текста используются
- сделай сетку шариков горизонтальной плиз
- сделай доп пункты по управлению и освещению, которые в чате я писал

2022-06-08 19:38 UTC, mrindieperson commented on RenderProject/engine/math/Light.h
> +	float solid_angle = M_PI * new_radius * new_radius;
Это вовсе не квадратичное затухание. Это деление плоского 2D угла на телесный 3D угол в коде, что впринципе невалидная операция. Нужно было подумать/погуглить, как найти телесный угол сферы.

2022-06-08 19:44 UTC, mrindieperson commented on RenderProject/engine/math/Light.h
> +	float solid_angle = M_PI * new_radius * new_radius;
А нет, это не деление 2D угла на 3D телесный, он попытался через PI*R^2 найти площадь круга и поделить, соответственно, на площадь сферы. Но вот только это не корректно из-за кривизны сферы, хотя направление мысли хотя бы более правильное. А задача в том заключается, чтобы найти телесный угол = найти **площадь шарового сегмента**, которая и равна телесному углу, если сфера единичная. Площадь единичной полусферы = телесный угол полусферы = 2PI

2022-06-08 19:58 UTC, mrindieperson commented on RenderProject/engine/window/controller.cpp
> +		scene.EV100 -= 1;
Перенеси в Controller::processInputs и меняй раз в кадр это значение, с учётом deltaTime, чтобы можно было плавно и с постоянной скоростью менять значение. Пусть меняется на 1 в секунду

2022-06-08 20:14 UTC, mrindieperson commented on RenderProject/engine/math/camera.h
>  	Matr m_viewProj = Matr(4), m_viewProjInv = Matr(4);
Ох, у тебя оказывается матрица - это вектор векторов, всё в динамической памяти разбросано. Ну, матрицы делают через шаблоны, где как template параметры передаётся число Row и Col, и хранится в матрице константный массив чисел, в том же месте где и объект. А у тебя нужно, чтобы прочитать одно значение в векторе, аж 2 раза прыгнуть по памяти, портя кеш CPU. Так как ты сделал точно не надо делать, потому что при написании рендерных систем мы должны заботиться о локальности данных.

У нас, конечно, не про создание мат либы интернатура, но кандидат в джуниоры шаблоны знать должен. Переделай свою матрицы через шаблоны, так не пойдёт, научишься с ними минимально работать по крайней мере, так как ты похоже не особо знаешь про них, а это необходимый навык. 

А вот если бы использовал мат либу, я бы не прикопался 😃

2022-06-08 20:21 UTC, mrindieperson commented on RenderProject/engine/window/Scene.cpp
> +void Scene::�orrectLight(Vec3& light)
Это не tone mapping, это весь postProcess у него тут, тонмаппинг только один этап.

2022-06-08 20:21 UTC, mrindieperson commented on RenderProject/engine/window/Scene.cpp
> +	light.e[2] = powf(light.e[2], 1.f / 2.2f);
Сделай отдельную функцию гамма-коррекции и весь вектор передавай в неё

2022-06-08 20:24 UTC, mrindieperson commented on RenderProject/engine/window/Scene.cpp
> +		result_light = nearest_material.emmission * 255.f;
Зачем тут HDR цвет умножается на 255? Это количество энергии света в сцене, абстрагированная от мониторов и пикселей, 255 должен появиться только в момент вывода LDR картинки на экран

2022-06-08 20:26 UTC, mrindieperson commented on RenderProject/engine/window/Scene.cpp
> +		if (nearest_material.roughness <= 0.1f && depth < 50)
Магическая константа, передавай число рекурсий как параметр и уменьшай до нуля каждый кадр

2022-06-08 20:27 UTC, mrindieperson commented on RenderProject/engine/window/Scene.cpp
> +		if (nearest_material.roughness <= 0.1f && depth < 50)
0.1f тоже сделай константой явной именнованной

2022-06-09 05:54 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/Scene.cpp
> +		result_light = nearest_material.emmission * 255.f;
++ уже заметил

2022-06-09 05:57 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/Scene.cpp
> +	light.e[2] = powf(light.e[2], 1.f / 2.2f);
++

2022-06-09 10:36 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/Scene.cpp
> +		if (nearest_material.roughness <= 0.1f && depth < 50)
++

2022-06-09 12:04 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/controller.cpp
> +		scene.EV100 -= 1;
++

2022-06-11 07:14 UTC, OleksandrGlushchuk commented on RenderProject/engine/math/camera.h
>  	Matr m_viewProj = Matr(4), m_viewProjInv = Matr(4);
++

2022-06-13 08:49 UTC, OleksandrGlushchuk commented
> * Почему нет уменьшения разрешения по осям в 2 раза с прошлого задания? Тормозит иначе при даже небольшом окне
> * Кнопка R не должна 100 раз в секунду переключать видимость гладких отражений пока зажата, один раз при нажатии только меняется , игнорируй повторные события, которые для печати текста используются
> * сделай сетку шариков горизонтальной плиз
> * сделай доп пункты по управлению и освещению, которые в чате я писал

++

2022-06-27 05:14 UTC, mrindieperson commented
Ты не сделал сетку шариков горизонтальной

2022-06-27 05:16 UTC, mrindieperson commented
Мог бы и сделать доп задание за такое время, пока я был занят 🙃

2022-06-27 05:31 UTC, mrindieperson requested changes

2022-06-27 05:31 UTC, mrindieperson commented on RenderProject/engine/window/Scene.cpp
> +				result_light += background_color;
Ты нашёл приходящий свет CalculateLighting или background_color, но взаимодействие через BRDF где?
BRDF при чём упрощается, потому что из-за гладкого случая интеграл вырождается, G == 1.0 (нет шероховатостей), D == 1.0 (BRDF в одном единственном направлении имеет значение не 0.0, 100% спекуляра отражается в одном направлении), фактор нормализации пропадает вместе с интегралом. Остаётся Fresnel, которого у тебя тут не видно

2022-06-27 05:31 UTC, mrindieperson commented on RenderProject/engine/math/Light.h
> +	if (DistancePointToLight >= light.light_radius)
Лучше убрать лишнее ветвление тут и сделать так, что DistancePointToLight = max(DistancePointToLight, light.light_radius), и кода меньше и без бранчинга лишнего

2022-06-27 05:31 UTC, mrindieperson commented on RenderProject/engine/math/Light.h
> +	Vec3 spec = F_LdotH * G * std::min<float>(1.f, solid_angle * D / (4.f * NdotV * NdotSpecL));
Выдели расчёт спекуляра в CookTorranceBRDF функцию, а диффуза в LambertBRDF, чтобы дублирования не было

2022-06-27 05:31 UTC, mrindieperson commented on RenderProject/engine/math/Light.h
>  	return x * x * (3 - 2 * x);
А это что :)

2022-06-27 05:31 UTC, mrindieperson commented on RenderProject/engine/math/Light.h
> +	Vec3 PointToSpecLight = approximateClosestSphereDir(intersects, r.direction, cosf(solid_angle), PointToLight, PointToLight.normalized(), DistancePointToLight, light.light_radius);
Ты смешиваешь опять плоский 2D угол (угловой размер) с телесным 3D углом. Нельзя cosf находить из solid_angle, возможно ты на мой косячный коммент посмотрел и буквально понял так

2022-06-27 06:43 UTC, OleksandrGlushchuk commented on RenderProject/engine/math/Light.h
> +	if (DistancePointToLight >= light.light_radius)
++

2022-06-27 06:58 UTC, OleksandrGlushchuk commented on RenderProject/engine/math/Light.h
> +	Vec3 spec = F_LdotH * G * std::min<float>(1.f, solid_angle * D / (4.f * NdotV * NdotSpecL));
++

2022-06-27 07:13 UTC, OleksandrGlushchuk commented on RenderProject/engine/math/Light.h
> +	Vec3 PointToSpecLight = approximateClosestSphereDir(intersects, r.direction, cosf(solid_angle), PointToLight, PointToLight.normalized(), DistancePointToLight, light.light_radius);
++

2022-06-27 08:27 UTC, OleksandrGlushchuk commented on RenderProject/engine/math/Light.h
>  	return x * x * (3 - 2 * x);
inline float smoothstep(float light_outerCutoff, float light_innerCutoff, float Ldir_dot_LtoPixel)
{
	float x = std::clamp((Ldir_dot_LtoPixel - light_outerCutoff) / (light_innerCutoff - light_outerCutoff), 0.f, 1.f);
	return x * x * (3.f - 2.f * x);
}

2022-06-27 08:29 UTC, OleksandrGlushchuk commented on RenderProject/engine/math/Light.h
>  	return x * x * (3 - 2 * x);
плавная интерполяция от innerCutoff к outerCutoff в spot_light источниках

2022-06-27 19:42 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/Scene.cpp
> +				result_light += background_color;
++

2022-06-28 07:59 UTC, OleksandrGlushchuk commented
> Ты не сделал сетку шариков горизонтальной

++

2022-06-28 23:13 UTC, mrindieperson commented on RenderProject/engine/window/Scene.cpp
>  	if (nearest_material.only_emmission)
Убери этот костыльный only_emmission. Ты ещё когда нашёл пересечение с объектом получил type его и можешь проверить там наперёд, а нужно ли будет считать освещение или только emission вернуть.

2022-06-28 23:15 UTC, mrindieperson commented on RenderProject/engine/window/Scene.cpp
> +		sum += CalculatePointLights(sphere_point_light, view_pos, nearest, nearest_material);
А зачем это дублирование кода в обоих ветках if для обычного освещения 😕

2022-06-28 23:20 UTC, mrindieperson commented on RenderProject/engine/window/Scene.cpp
> +				refl = Vec3::lerp(Vec3(0, 0, 0), refl, ((MAX_REFLECTIVE_ROUGHNESS - nearest_material.roughness) * 1.f / MAX_REFLECTIVE_ROUGHNESS));
Можно просто умножить на параметр интерполяции само значение refl, зачем тут лерп

2022-06-28 23:23 UTC, mrindieperson commented on RenderProject/engine/math/Matr.h
> +template<int sz>
template константы обычно пишут большими буквами как константы в коде. типо SIZE. Или просто уж с большой буквы. Если тип, то просто с большой буквы. То есть template\<typename T, typename TAllocator, int Size\>, например

2022-06-29 00:26 UTC, mrindieperson commented on RenderProject/engine/math/Light.h
> +	Vec3 F_LdotH = fresnel(Vec3::dot(PtoL_normalized, HalfCameraLight), nearest_mat.F0);
У тебя неправильные аргументы для Fresnel. Подумай ещё раз, как свет отражается от поверхности

2022-06-29 00:29 UTC, mrindieperson commented on RenderProject/engine/math/Light.h
> +	return input_light * NdotL * F_LdotH;
NdotL не нужен, так как интеграла здесь нет и тут другой случай. Да, проекция площади убывает под углом, но при взгляде под углом на зеркало площадь охватываемой поверхности в одном пикселе обратно пропорционально увеличивается, поэтому умножение на NdotL отменяется делением на NdotV, а NdotL == NdotV при гладком зеркальном отражении. Иначе если бы смотрели на зеркала под углом, то мы бы не видели отражения того же цвета, а отражение было бы темнее вплоть до чёрного цвета при остром угле.

2022-06-29 00:31 UTC, mrindieperson commented on RenderProject/engine/window/Scene.cpp
> +		sampled_ray.direction.e[0] = sinf_theta * cosf(phi);
Зачем заинлайнил код генерации направлении, вынеси его в функцию fibonacciHemisphereDirection

2022-06-29 00:33 UTC, mrindieperson commented on RenderProject/engine/window/Scene.cpp
> +			indirect_lighting += CalculateBRDF( scene_ambient, d_omega, sampled_ray.direction, view_pos, nearest.point, nearest.normal, nearest_material) *
Сделай проверку интегрирования. Вместо CalculateBRDF прибавляй dot(N, sampleDir). То есть это будет нахождением интеграла косинуса по полусфере. Если всё правильно, должно получиться PI (поэтому в Lambert Diffuse делится на PI, чтобы нормализовать энергию)

2022-06-29 00:35 UTC, mrindieperson commented
Добавь пару кубиков в сцену

2022-06-29 08:33 UTC, OleksandrGlushchuk commented
> Добавь пару кубиков в сцену

++

2022-06-29 08:34 UTC, OleksandrGlushchuk commented on RenderProject/engine/math/Matr.h
> +template<int sz>
++

2022-06-29 08:36 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/Scene.cpp
> +		sum += CalculatePointLights(sphere_point_light, view_pos, nearest, nearest_material);
++

2022-06-29 08:40 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/Scene.cpp
> +				refl = Vec3::lerp(Vec3(0, 0, 0), refl, ((MAX_REFLECTIVE_ROUGHNESS - nearest_material.roughness) * 1.f / MAX_REFLECTIVE_ROUGHNESS));
++

2022-06-29 08:57 UTC, OleksandrGlushchuk commented on RenderProject/engine/math/Light.h
> +	return input_light * NdotL * F_LdotH;
++

2022-06-29 10:26 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/Scene.cpp
>  	if (nearest_material.only_emmission)
++

2022-06-29 10:34 UTC, OleksandrGlushchuk commented on RenderProject/engine/math/Light.h
> +	Vec3 F_LdotH = fresnel(Vec3::dot(PtoL_normalized, HalfCameraLight), nearest_mat.F0);
Исправил на 
Vec3 F_LdotN = fresnel(NdotL, nearest_mat.F0);

2022-06-29 10:44 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/Scene.cpp
> +		sampled_ray.direction.e[0] = sinf_theta * cosf(phi);
++

2022-06-29 13:05 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/Scene.cpp
> +			indirect_lighting += CalculateBRDF( scene_ambient, d_omega, sampled_ray.direction, view_pos, nearest.point, nearest.normal, nearest_material) *
++

2022-06-29 23:27 UTC, mrindieperson commented on RenderProject/engine/window/Scene.cpp
>  			//if there is another object between the object and the light source
У тебя поиск пересечения с объектами сцены для теней дублируется в каждой функции освещения, это нужно выносить в отдельную функцию поиска пересечения, она разве у тебя не была?

2022-06-29 23:29 UTC, mrindieperson commented on RenderProject/engine/math/Light.h
> +	Vec3 PointToSpecLight = approximateClosestSphereDir(intersects, r.direction, cosf(FindAngularDiameter(light.light_radius,DistancePointToLight)),
Ты аж две тяжёлые тригонометрические операции заюзал для нахождения косинуса угла. Подумай, как убрать вообще тут вызов cosf и atanf

2022-06-29 23:33 UTC, mrindieperson commented on RenderProject/engine/math/Light.h
> +	r.direction = Vec3::Reflect(-PointToLight.normalized(), nearest_normal);
Посмотри на спекулярные отражения, их просто нет или они не в том месте. А всё потому что тут неправильный аргумент передал в Reflect, посмотри на картинку в чатике ещё раз для approximateClosestSphereDir

2022-06-29 23:36 UTC, mrindieperson commented
сделай источники света не такими прям огромными, но и не маленькими

2022-06-29 23:44 UTC, mrindieperson commented on RenderProject/engine/window/Scene.cpp
> +Vec3 Scene::CalculateLighting(const ray &ray_to_object, const Vec3& view_pos, const math::Intersection& nearest, const Material& nearest_material, const int &depth)
ray_to_object и MAX_DEPTH_FOR_GI не используются

2022-06-29 23:51 UTC, mrindieperson commented on RenderProject/engine/window/Scene.cpp
> +			indirect_lighting += CalculateBRDF( CalculateGlobalIllumination(number_of_samples, sampled_ray, nearest.point, sampled_nearest, sampled_nearest_material, depth - 1),
Во-первых, я говорил можно не делать GI рекурсивным, так как это займёт слишком много времени.

Во-вторых, что тут вообще считается? Если найдено пересечение со сценой, что является входной энергий? Почему ты внутри функции нахождения GI интегрируешь значения CalculateGlobalIllumination? У тебя на поверхность падают N лучей, которые либо являются цветом неба, либо светом, отражённым от других поверхностей, если есть пересечение, а это функция CalculateLighting

В-третьих, ты в CalculateBRDF передаёшь view_pos камеры. И у тебя в итоге считается освещение так, что свет, отражённый от вторичных поверхностей на первичную имеют неправильный V вектор, потому что V вектор должен быть, логично, от вторичной поверхности к первичной, а у тебя тут от вторичной поверхности к камере

2022-06-30 04:50 UTC, OleksandrGlushchuk commented
> сделай источники света не такими прям огромными, но и не маленькими

++

2022-06-30 05:10 UTC, OleksandrGlushchuk commented on RenderProject/engine/math/Light.h
> +	Vec3 PointToSpecLight = approximateClosestSphereDir(intersects, r.direction, cosf(FindAngularDiameter(light.light_radius,DistancePointToLight)),
++

2022-06-30 06:24 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/Scene.cpp
>  			//if there is another object between the object and the light source
++

2022-07-01 08:28 UTC, OleksandrGlushchuk commented on RenderProject/engine/math/Light.h
> +	r.direction = Vec3::Reflect(-PointToLight.normalized(), nearest_normal);
++

2022-07-01 20:59 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/Scene.cpp
> +			indirect_lighting += CalculateBRDF( CalculateGlobalIllumination(number_of_samples, sampled_ray, nearest.point, sampled_nearest, sampled_nearest_material, depth - 1),
++

2022-07-03 18:05 UTC, mrindieperson approved these changes
Аппрув наперёд 👍 

UPD: по ошибке в твой ПР написал, хотел в другой

2022-07-03 18:49 UTC, mrindieperson commented on RenderProject/engine/window/Scene.cpp
> +		result_light = nearest_material.emmission + (global_ambient) * nearest_material.albedo + sum;
Нет, тут не нужен альбедо, нет такой формулы, где интеграл BRDF ещё дополнительно умножается на альбедо, альбедо влияет на диффуз и уже внутри интеграла учтено

2022-07-03 18:51 UTC, mrindieperson commented on RenderProject/engine/window/Scene.cpp
> +		result_light = nearest_material.emmission + (global_ambient) * nearest_material.albedo + sum;
ambient константа - это просто грубая дешёвая аппроксимация всего интеграла освещения

2022-07-03 18:54 UTC, mrindieperson commented on RenderProject/engine/window/Scene.cpp
> +			indirect_lighting += CalculateBRDF(scene_ambient, d_omega, sampled_ray.direction, view_pos, nearest.point, nearest.normal, nearest_material) *
Убери дублирование кода, у тебя меняется только значение входящей энергии света

2022-07-03 18:56 UTC, mrindieperson commented on RenderProject/engine/window/Scene.cpp
> +				reflected_light = CalculateSmoothBRDF(background_color, r.direction.normalized(), view_pos, nearest.point, nearest.normal, nearest_material) * smooth_reflection_attenuate;
Убери дублирование кода, меняется только значение энергии входящей.
(reflected_nearest.point - nearest.point).normalized() == r.direction, разве нет?
И зачем там r.direction.normalized(), если направление луча итак нормализовано, если ray_to_object.direction уже был нормализован

2022-07-03 18:57 UTC, mrindieperson commented on RenderProject/engine/window/Scene.cpp
> +		result_light = nearest_material.emmission + scene_ambient * nearest_material.albedo + sum;
Этот код зачем тоже дублируется, если только нужно добавить ambient или GI, в зависимости от условия

2022-07-03 18:58 UTC, mrindieperson commented on RenderProject/engine/window/Scene.cpp
> +				reflected_light = CalculateSmoothBRDF(background_color, r.direction.normalized(), view_pos, nearest.point, nearest.normal, nearest_material) * smooth_reflection_attenuate;
Аналогично дублирование

2022-07-04 08:48 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/Scene.cpp
> +		result_light = nearest_material.emmission + (global_ambient) * nearest_material.albedo + sum;
++

2022-07-04 09:18 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/Scene.cpp
> +			indirect_lighting += CalculateBRDF(scene_ambient, d_omega, sampled_ray.direction, view_pos, nearest.point, nearest.normal, nearest_material) *
++

2022-07-04 09:37 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/Scene.cpp
> +				reflected_light = CalculateSmoothBRDF(background_color, r.direction.normalized(), view_pos, nearest.point, nearest.normal, nearest_material) * smooth_reflection_attenuate;
++

2022-07-04 09:38 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/Scene.cpp
> +				reflected_light = CalculateSmoothBRDF(background_color, r.direction.normalized(), view_pos, nearest.point, nearest.normal, nearest_material) * smooth_reflection_attenuate;
++

2022-07-04 09:42 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/Scene.cpp
> +		result_light = nearest_material.emmission + scene_ambient * nearest_material.albedo + sum;
++

2022-07-05 11:19 UTC, DmitrySarafaniuk approved these changes
👍

2022-07-05 11:21 UTC, merged