homework-5
OleksandrGlushchuk/Homeworks1 pull request #5
Opened 2022-07-13 18:51 UTC by OleksandrGlushchuk

2022-07-14 09:37 UTC, DmitrySarafaniuk commented
Debug версия падает на переводе кватерниона в матрицу. Проверь, пожалуйста.

2022-07-14 09:37 UTC, DmitrySarafaniuk commented
Добавь, пожалуйста, возможность переключаться между режимами семплинга, как было указано в задании.

2022-07-14 09:38 UTC, DmitrySarafaniuk commented
Переназови CameraBuffer на PerFrame буфер. Он подразумевает, что тут будут не только данные камеры в дальнейшем. Такие объекты, которые с большой долей вероятности будут использоваться везде (глобальный буфер, базовый семплер), запиши в globals.hlsli и делай его #include в шейдерах, где эти данные необходимы. 
Можно даже этот буфер задавать в C++ хедер файлом и включать в код шейдера.

2022-07-14 12:52 UTC, OleksandrGlushchuk commented
> Переназови CameraBuffer на PerFrame буфер. Это будет глобальный буфер, о котором говорилось в задании, и он подразумевает, что тут будут не только данные камеры в дальнейшем. Такие объекты, которые с большой долей вероятности будут использоваться везде (глобальный буфер, базовый семплер), запиши в globals.hlsli и делай его #include в шейдерах, где эти данные необходимы. Можно даже этот буфер задавать в C++ хедер файлом и включать в код шейдера.

++

2022-07-14 19:00 UTC, DmitrySarafaniuk commented on RenderProject/engine/render/TextureManager.cpp
> +		engine::s_deviceContext->PSSetSamplers(0, 1, &m_samplerState[samplerStateKey].ptr());
Поставь assert на существования ключа для семплера и текстуры.

2022-07-14 19:01 UTC, DmitrySarafaniuk commented on RenderProject/engine/window/window.cpp
> +		depthStencilDesc.DepthFunc = D3D11_COMPARISON_FUNC::D3D11_COMPARISON_LESS_EQUAL;
Лучше используй reversed-z. В шейдерах нужно будет сделать изменения аналогично.

2022-07-14 20:03 UTC, OleksandrGlushchuk commented
> Добавь, пожалуйста, возможность переключаться между режимами семплинга, как было указано в задании.

++

2022-07-14 20:42 UTC, OleksandrGlushchuk commented on RenderProject/engine/render/TextureManager.cpp
> +		engine::s_deviceContext->PSSetSamplers(0, 1, &m_samplerState[samplerStateKey].ptr());
++

2022-07-14 22:06 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/window.cpp
> +		depthStencilDesc.DepthFunc = D3D11_COMPARISON_FUNC::D3D11_COMPARISON_LESS_EQUAL;
++

2022-07-15 08:27 UTC, DmitrySarafaniuk commented
Посмотри буфер, который ты не меняешь (например, вершинный буфер в Triangle::CreateMesh, Sky::CreateMesh и Cube::CreateMesh), и сделай их D3D11_USAGE_IMMUTABLE.

2022-07-15 08:29 UTC, DmitrySarafaniuk commented on RenderProject/engine/d3dobjects/CubeD3D.cpp
> +	auto vertexBufferDesc = CD3D11_BUFFER_DESC(m_mesh.MeshSize(), D3D11_BIND_VERTEX_BUFFER);
Сделай, пожалуйста, размер куба со стороной 1, чтобы не нужно было масштабирование в Cube и CubeD3D делить на 2 - это не интуитивно.

2022-07-15 09:05 UTC, OleksandrGlushchuk commented on RenderProject/engine/d3dobjects/CubeD3D.cpp
> +	auto vertexBufferDesc = CD3D11_BUFFER_DESC(m_mesh.MeshSize(), D3D11_BIND_VERTEX_BUFFER);
++ еще текстура была перевернутой то исправил

2022-07-15 09:35 UTC, OleksandrGlushchuk commented
> Посмотри буфер, который ты не меняешь (например, вершинный буфер в Triangle::CreateMesh, Sky::CreateMesh и Cube::CreateMesh), и сделай их D3D11_USAGE_IMMUTABLE.

++

2022-07-18 17:09 UTC, mrindieperson commented
ControllerD3D, не знаю, зачем его так назвал, не должен делать ничего с графикой, он должен просто всё также управлять сценой, к API образайся внутри Scene::draw(), не надо в Controller смешивать управление и графику

2022-07-18 17:09 UTC, mrindieperson requested changes

2022-07-18 17:09 UTC, mrindieperson commented on RenderProject/engine/render/TextureManager.h
> +		static TextureManager m_instance;
Сделай как в чатике писал, плиз, иначе откуда у тебя init() вызывается?
Инициализируй все синглтоны однообразно по порядку в Engine::init(), но не в main.cpp

2022-07-18 17:09 UTC, mrindieperson commented on RenderProject/engine/window/controller.h
> +		engine::DxResPtr<ID3D11Buffer> m_perFrameBuffer;
Это должно быть в синглтоне Globals, это общий рендерный ресурс, зачем это в windows::Controller засовывать

2022-07-18 17:09 UTC, mrindieperson commented on RenderProject/engine/window/controller.cpp
> +		engine::s_deviceContext->VSSetConstantBuffers(0, 1, &m_perFrameBuffer.ptr());
Тут должно быть Globals::bind(), который внутри устанавливает глобальный униформ буффер + общие Sampler States

2022-07-18 17:09 UTC, mrindieperson commented on RenderProject/engine/window/Scene.h
> +		void Draw();
Сделай просто один Draw без Redraw

2022-07-18 17:09 UTC, mrindieperson commented on RenderProject/engine/d3dobjects/CubeD3D.cpp
> +	engine::TextureManager::instance().SetSamplerState(*m_samplerStateKeyPtr);
Общие SamplerState один раз за кадр должен быть установлены, не нужно на каждую текстуру делать по семплеру

2022-07-18 17:09 UTC, mrindieperson commented on RenderProject/engine/render/TextureManager.h
> +		std::map<std::string, engine::DxResPtr<ID3D11SamplerState> > m_samplerState;
shared SamplerStates в Globals должны быть

2022-07-18 17:09 UTC, mrindieperson commented on RenderProject/engine/d3dobjects/Sky.cpp
> +	engine::TextureManager::instance().SetTexture("sky");
Нет, не надо искать текстуру в TextureManager, ты уже с его помощью её загрузил и получил ссылку, сохрани её в Sky и бинди её не обращаясь к TextureManager, в Sky всё для рендера уже известно, и шейдеры, и текстура, m_vertexShader ты же хранишь тут, также и текстура

2022-07-18 17:09 UTC, mrindieperson commented on RenderProject/engine/window/controller.cpp
> +	void ControllerD3D::InitSamplerStates()
Это должно быть инициализацией в Globals

2022-07-18 17:09 UTC, mrindieperson commented on RenderProject/engine/window/controller.cpp
> +			UpdateCameraBuffer();
Графическое API точно не должно вызываться из функции обработки инпутов.

UpdateCameraBuffer должен в DrawScene, до того, как вызывается Globals::bind(), который биндит shared семплеры и per frame buffer

2022-07-19 10:15 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/Scene.h
> +		void Draw();
++

2022-07-19 10:23 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/controller.h
> +		engine::DxResPtr<ID3D11Buffer> m_perFrameBuffer;
++

2022-07-19 10:26 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/controller.cpp
> +			UpdateCameraBuffer();
++

2022-07-19 10:50 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/controller.cpp
> +	void ControllerD3D::InitSamplerStates()
++

2022-07-19 12:00 UTC, OleksandrGlushchuk commented on RenderProject/engine/d3dobjects/Sky.cpp
> +	engine::TextureManager::instance().SetTexture("sky");
++

2022-07-19 13:38 UTC, OleksandrGlushchuk commented on RenderProject/engine/render/TextureManager.h
> +		std::map<std::string, engine::DxResPtr<ID3D11SamplerState> > m_samplerState;
++

2022-07-19 13:39 UTC, OleksandrGlushchuk commented on RenderProject/engine/d3dobjects/CubeD3D.cpp
> +	engine::TextureManager::instance().SetSamplerState(*m_samplerStateKeyPtr);
++

2022-07-19 13:39 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/controller.cpp
> +		engine::s_deviceContext->VSSetConstantBuffers(0, 1, &m_perFrameBuffer.ptr());
++

2022-07-19 13:43 UTC, OleksandrGlushchuk commented on RenderProject/engine/render/TextureManager.h
> +		static TextureManager m_instance;
++

2022-07-20 18:04 UTC, mrindieperson commented on RenderProject/engine/objects/Cube.cpp
> +	engine::s_deviceContext->IASetInputLayout(s_inputLayout.ptr());
По условию нужно рисовать треугольник без вертекс буффера, Input Layout ставь NULL. В вершинном шейдере генерируй по индексу вершины треугольника

2022-07-20 18:10 UTC, mrindieperson commented on RenderProject/engine/window/controller.cpp
> +		HRESULT result = engine::s_device->CreateBuffer(&perFrameBufferDesc, nullptr, engine::Globals::instance().m_perFrameBuffer.reset());
Ну зачем ты поле Globals инициализируешь из Controller? В Globals::init это должно делаться

2022-07-20 18:11 UTC, mrindieperson commented on RenderProject/engine/window/controller.cpp
> +		engine::Globals::instance().InitSamplerStates();
InitSamplerStates должен из Globals::init вызываться

2022-07-20 18:11 UTC, mrindieperson commented on RenderProject/engine/render/globals.cpp
> +	void Globals::InitTextures()
Зачем это инициализирует Globals, это не глобальные общие ресурсы

2022-07-20 18:12 UTC, mrindieperson commented on RenderProject/engine/render/globals.cpp
> +	void Globals::InitShaders()
Зачем это инициализирует Globals, это не глобальные общие ресурсы

2022-07-20 18:12 UTC, mrindieperson commented on RenderProject/engine/render/globals.cpp
> +		engine::ShaderManager::instance().InitShaders(L"source/shaders/sky.hlsl", "sky");
Шейдер неба инициализируй в Sky::init

2022-07-20 18:12 UTC, mrindieperson commented on RenderProject/engine/render/globals.cpp
> +		engine::TextureManager::instance().InitTexture(L"source/textures/skymap.dds", "sky");
Текстуру неба инициализируй в Sky::init или в SetTexture, но не из Globals, зачем Globals знать про существование неба? А если его нет?

2022-07-20 18:16 UTC, mrindieperson commented on RenderProject/engine/window/controller.cpp
> +			engine::ShaderManager::instance().GetShaderBlobs("sky", Sky::s_vertexShaderBlob, Sky::s_pixelShaderBlob);
Это всё должно быть просто в sky.init()

2022-07-20 18:16 UTC, mrindieperson commented on RenderProject/engine/window/controller.cpp
> +		InitPerFrameBuffer();
Это должно было вызваться из Globals::init, у тебя сейчас какое-то спаггети из инициализаций, ресурсы разных классов и уровней инициализируется вообще в других местах

2022-07-20 18:17 UTC, mrindieperson commented on RenderProject/engine/render/ShaderManager.cpp
> +		s_instance = new ShaderManager;
Ты здесь аллоцируешь поле и всё, а где shared ресурсы? Per Frame Buffer? Shared SamplerState?

2022-07-21 07:00 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/controller.cpp
> +		engine::Globals::instance().InitSamplerStates();
++

2022-07-21 07:26 UTC, OleksandrGlushchuk commented on RenderProject/engine/render/globals.cpp
> +	void Globals::InitTextures()
++

2022-07-21 07:26 UTC, OleksandrGlushchuk commented on RenderProject/engine/render/globals.cpp
> +	void Globals::InitShaders()
++

2022-07-21 07:27 UTC, OleksandrGlushchuk commented on RenderProject/engine/render/globals.cpp
> +		engine::ShaderManager::instance().InitShaders(L"source/shaders/sky.hlsl", "sky");
++

2022-07-21 07:27 UTC, OleksandrGlushchuk commented on RenderProject/engine/render/globals.cpp
> +		engine::TextureManager::instance().InitTexture(L"source/textures/skymap.dds", "sky");
++

2022-07-21 07:27 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/controller.cpp
> +			engine::ShaderManager::instance().GetShaderBlobs("sky", Sky::s_vertexShaderBlob, Sky::s_pixelShaderBlob);
++

2022-07-21 08:11 UTC, OleksandrGlushchuk commented on RenderProject/engine/render/ShaderManager.cpp
> +		s_instance = new ShaderManager;
++

2022-07-21 08:11 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/controller.cpp
> +		InitPerFrameBuffer();
++

2022-07-21 08:11 UTC, OleksandrGlushchuk commented on RenderProject/engine/window/controller.cpp
> +		HRESULT result = engine::s_device->CreateBuffer(&perFrameBufferDesc, nullptr, engine::Globals::instance().m_perFrameBuffer.reset());
++

2022-07-21 09:20 UTC, OleksandrGlushchuk commented on RenderProject/engine/objects/Cube.cpp
> +	engine::s_deviceContext->IASetInputLayout(s_inputLayout.ptr());
++

2022-07-21 11:02 UTC, mrindieperson commented on RenderProject/engine/objects/Sky.h
> +	static void InitShaders();
Зачем у тебя тут всё static? А если у нас два неба и мы хотим по нажатию клавиши переключать их? Про Cube и Triangle я ничего не говорю, так как в следующем задании они удалятся

2022-07-21 11:37 UTC, OleksandrGlushchuk commented on RenderProject/engine/objects/Sky.h
> +	static void InitShaders();
++

2022-07-21 11:41 UTC, mrindieperson approved these changes
Approved :+1:

2022-07-21 11:45 UTC, DmitrySarafaniuk approved these changes
👍

2022-07-21 11:45 UTC, merged